use lalrpop_util::ParseError;

use crate::lexer::*;
use crate::ast::*;

grammar<'s, 'e>(errors: &'e mut Vec<ParseError<usize, Token<'s>, ()>>);

extern 
{
    type Location = usize;
    type Error = ();

    enum Token<'s> 
    {
        "[" => Token::LeftSqr,
        "]" => Token::RightSqr,
        "{" => Token::LeftBrace,
        "}" => Token::RightBrace,
        "(" => Token::LeftParen,
        ")" => Token::RightParen,
        ";" => Token::Semicolon,
        ":" => Token::Colon,
        "," => Token::Comma,
        "." => Token::Dot,
        "?" => Token::Question,

        "+" => Token::Plus,
        "-" => Token::Minus,
        "/" => Token::ForSlash,
        "*" => Token::Star,

        "=" => Token::Eq,
        "==" => Token::EqEq,
        "!" => Token::Bang,
        "!=" => Token::BangEq,
        ">" => Token::Greater,
        ">=" => Token::GreaterEq,
        "<" => Token::Lesser,
        "<=" => Token::LesserEq,
        "&&" => Token::And,
        "||" => Token::Or,

        "Int" => Token::Int,
        "Float" => Token::Float,
        "Bool" => Token::Bool,
        "print" => Token::Print,
        "compt" => Token::Compt,
        "if" => Token::If,
        "else" => Token::Else,
        "while" => Token::While,
        "for" => Token::For,
        "entt" => Token::Entt,

        "iden" => Token::Identifier(<&'s [u8]>),
        "literal" => Token::Literal(<Literal>),

        "<err>" => Token::Error
    }
}

pub PROG: AST<'s> =
{
    <stmts:STMT*> => AST(stmts)
}

STMT: Stmt<'s> =
{
    "entt" <id:"iden"> ":" <typ:ENTT> "=" <expr:ASSN> ";" => Stmt::Decl(typ, id, expr),
    <expr:ASSN> ";" => Stmt::Expr(expr),
    <err:!> ";" =>
    {
        errors.push(err.error);
        Stmt::Error
    },
    <err:"<err>"> => Stmt::Error
}

ENTT: EnttType =
{
    <c:COMPT> => EnttType::Compt(c),
    "[" "]" => EnttType::Unit
}

COMPT: ComptType =
{
    "Int" => ComptType::Int,
    "Float" => ComptType::Float,
    "Bool" => ComptType::Bool,
}

ASSN: Expr<'s> =
{
    <l:TERN> "=" <r:ASSN> => Expr::Call(FnName::Assign, vec![l, r]),
    <e:TERN> => e
}

TERN: Expr<'s> =
{
    <p:LOG> "?" <i:TERN> ":" <e:TERN> => Expr::Call(FnName::Ternary, vec![p, i, e]),
    <e:LOG> => e
}

LOG: Expr<'s> =
{
    <l:LOG> "&&" <r:EQ> => Expr::Call(FnName::And, vec![l, r]),
    <l:LOG> "||" <r:EQ> => Expr::Call(FnName::Or, vec![l, r]),
    <e:EQ> => e
}

EQ: Expr<'s> =
{
    <l:EQ> "==" <r:INEQ> => Expr::Call(FnName::EqualTo, vec![l, r]),
    <l:EQ> "!=" <r:INEQ> => Expr::Call(FnName::NotEqualTo, vec![l, r]),
    <e:INEQ> => e
}

INEQ: Expr<'s> =
{
    <l:INEQ> ">" <r:ADD> => Expr::Call(FnName::Greater, vec![l, r]),
    <l:INEQ> "<" <r:ADD> => Expr::Call(FnName::Lesser, vec![l, r]),
    <l:INEQ> ">=" <r:ADD> => Expr::Call(FnName::GreaterEq, vec![l, r]),
    <l:INEQ> "<=" <r:ADD> => Expr::Call(FnName::LesserEq, vec![l, r]),
    <e:ADD> => e
}

ADD: Expr<'s> =
{
    <l:ADD> "+" <r:FACT> => Expr::Call(FnName::Add, vec![l, r]),
    <l:ADD> "-" <r:FACT> => Expr::Call(FnName::Sub, vec![l, r]),
    <e:FACT> => e
}

FACT: Expr<'s> =
{
    <l:FACT> "*" <r:UN> => Expr::Call(FnName::Mul, vec![l, r]),
    <l:FACT> "/" <r:UN> => Expr::Call(FnName::Div, vec![l, r]),
    <e:UN> => e
}

UN: Expr<'s> =
{
    "!" <e:UN> => Expr::Call(FnName::Not, vec![e]),
    "-" <e:UN> => Expr::Call(FnName::Negate, vec![e]),
    "print" <e:UN> => Expr::Call(FnName::Print, vec![e]),
    <e:GRP> => e
}

GRP: Expr<'s> =
{
    "(" <e:ASSN> ")" => e,
    <e:ENTLIT> => e,
    <e:"iden"> => Expr::Identifier(e)
}

ENTLIT: Expr<'s> =
{
    <e:"literal"> => Expr::Literal(e)
}